### ISSUE TITLE
nihui大佬，syncgap-mode 是啥意思？

### ISSUE THREAD

**Issue by zhouhang95** [nihui/realcugan-ncnn-vulkan#11]
RT

**Comment by lj1995-computer-vision** [comment]
syncgap-mode是一个速度和效果的trade-off。由于省显存需要，需要对全图进行分块分别处理，分别处理最后汇总成处理完的大图，整个pipeline中，有一些位置需要对一些gap参数同步（sync-gap）
0最快：不同patch之间可能造成切割线
1最慢：效果无损
2速度适中：稍微对背景虚化的保留损失一点，纹理没什么损失
3最快：相比2对背景虚化的保留损失更多一点，纹理没什么损失
我的建议：
1、如果画面整体模糊程度一致，预实验发现没有切割线痕迹，可用mode0
2、如果有切割线（或者凭经验肯定有，不用做实验了），那么根据经验（或者实验）判断画面有无虚化部分：
如果没有，可直接用mode3
3、如果有，可以拿有背景虚化的图试试1和2，对比2的损失是否可以接受，也可以对比看看3是否可以接受
4、拿有代表性的样本选定完mode后，使用该mode对全片进行超分

**Comment by lj1995-computer-vision** [comment]
> RT
@zhouhang95 
syncgap-mode是一个速度和效果的trade-off。由于省显存需要，需要对全图进行分块分别处理，分别处理最后汇总成处理完的大图，整个pipeline中，有一些位置需要对一些gap参数同步（sync-gap）
0最快：不同patch之间可能造成切割线
1最慢：效果无损
2速度适中：稍微对背景虚化的保留损失一点，纹理没什么损失
3最快：相比2对背景虚化的保留损失更多一点，纹理没什么损失
我的建议：
1、如果画面整体模糊程度一致，预实验发现没有切割线痕迹，可用mode0
2、如果有切割线（或者凭经验肯定有，不用做实验了），那么根据经验（或者实验）判断画面有无虚化部分：
如果没有，可直接用mode3
3、如果有，可以拿有背景虚化的图试试1和2，对比2的损失是否可以接受，也可以对比看看3是否可以接受
4、拿有代表性的样本选定完mode后，使用该mode对全片进行超分

**Comment by zhouhang95** [comment]
ok

**Comment by ArchieMeng** [comment]
相比起含义，我更想知道syncgap-mode的实现中，每个阶段具体都做了什么。因为我这边Android移植的话，这部分可能要在Java层面去实现。
