### ISSUE TITLE
为什么我cmake --build . -j 4的结果是这个

### ISSUE THREAD

**Issue by misiku** [nihui/realcugan-ncnn-vulkan#12]

**Comment by 171qe** [comment]
build$cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_BUILD_EXAMPLES=OFF -DNCNN_PLATFORM_API=OFF -DNCNN_SIMPLEOCV=ON ../src

-- The C compiler identification is Clang 13.0.1
-- The CXX compiler identification is Clang 13.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenMP_C: -fopenmp=libomp (found version "5.0")
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0")
-- Found OpenMP: TRUE (found version "5.0")
-- Found Vulkan: /data/data/com.termux/files/usr/lib/libvulkan.so
-- CMAKE_INSTALL_PREFIX = /usr/local
-- NCNN_VERSION_STRING = 1.0.20220316
-- Performing Test NCNN_COMPILER_SUPPORT_ARM82_FP16
-- Performing Test NCNN_COMPILER_SUPPORT_ARM82_FP16 - Success
-- Performing Test NCNN_COMPILER_SUPPORT_ARM82_FP16_DOTPROD
-- Performing Test NCNN_COMPILER_SUPPORT_ARM82_FP16_DOTPROD - Success
-- Target arch: arm
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found OpenMP_C: -fopenmp=libomp (found version "5.0")
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0")
-- Found WebP: /data/data/com.termux/files/usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /data/data/com.termux/files/home/realcugan-ncnn-vulkan/build

build$cmake --build . -j 4

[  1%] Building CXX object ncnn/glslang/OGLCompilersDLL/CMakeFiles/OGLCompiler.dir/InitializeDll.cpp.o
[  1%] Building CXX object ncnn/glslang/glslang/CMakeFiles/GenericCodeGen.dir/GenericCodeGen/CodeGen.cpp.o
[  1%] Building CXX object ncnn/glslang/glslang/OSDependent/Unix/CMakeFiles/OSDependent.dir/ossource.cpp.o
[  1%] Preprocessing shader source convolution.comp
[  1%] Preprocessing shader source convolution_1x1s1d1.comp
[  1%] Preprocessing shader source convolution_pack1to4.comp
[  1%] Linking CXX static library libOSDependent.a
......
[ 99%] Building CXX object ncnn/src/CMakeFiles/ncnn.dir/layer/arm/pixelshuffle_arm_arm82.cpp.o
[ 99%] Linking CXX static library libncnn.a
[ 99%] Built target ncnn
[ 99%] Building CXX object CMakeFiles/realcugan-ncnn-vulkan.dir/realcugan.cpp.o
[ 99%] Building CXX object CMakeFiles/realcugan-ncnn-vulkan.dir/main.cpp.o
[100%] Linking CXX executable realcugan-ncnn-vulkan
[100%] Built target realcugan-ncnn-vulkan

build$ls

CMakeCache.txt         ncnn                               realcugan_4x_postproc_tta.text2hex.txt  realcugan_preproc.text2hex.txt
CMakeFiles             out.png                              realcugan_postproc.comp.hex.h             realcugan_preproc_tta.comp.hex.h
Makefile               realcugan-ncnn-vulkan        realcugan_postproc.text2hex.txt             realcugan_preproc_tta.text2hex.txt
cmake_install.cmake                                         realcugan_4x_postproc.comp.hex.h        realcugan_postproc_tta.comp.hex.h
compile_commands.json                                  realcugan_4x_postproc.text2hex.txt        realcugan_postproc_tta.text2hex.txt
include                                                              realcugan_4x_postproc_tta.comp.hex.h  realcugan_preproc.comp.hex.h

build$./realcugan-ncnn-vulkan -i ../images/0.jpg -o out.png

[0 Mali-G57 MC3]  queueC=0[2]  queueG=0[2]  queueT=0[2]
[0 Mali-G57 MC3]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Mali-G57 MC3]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Mali-G57 MC3]  subgroup=16  basic=1  vote=1  ballot=1  shuffle=0
fopen /data/data/com.termux/files/home/realcugan-ncnn-vulkan/build/models-se/up2x-conservative.param failed
fopen /data/data/com.termux/files/home/realcugan-ncnn-vulkan/build/models-se/up2x-conservative.bin failed
find_blob_index_by_name in0 failed
Try
find_blob_index_by_name out0 failed
Try

$vulkaninfo

==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.205


Instance Extensions: count = 10
===============================
        VK_EXT_debug_report                    : extension revision 9
        VK_EXT_swapchain_colorspace            : extension revision 3
        VK_KHR_android_surface                 : extension revision 6
        VK_KHR_device_group_creation           : extension revision 1
        VK_KHR_external_fence_capabilities     : extension revision 1
        VK_KHR_external_memory_capabilities    : extension revision 1
        VK_KHR_external_semaphore_capabilities : extension revision 1
        VK_KHR_get_physical_device_properties2 : extension revision 1
        VK_KHR_get_surface_capabilities2       : extension revision 1
        VK_KHR_surface                         : extension revision 25
......
VkPhysicalDeviceTextureCompressionASTCHDRFeaturesEXT:
-----------------------------------------------------
        textureCompressionASTC_HDR = true

VkPhysicalDeviceVariablePointersFeatures:
-----------------------------------------
        variablePointersStorageBuffer = true
        variablePointers              = true

**Comment by nihui** [comment]
把 models 里的文件夹放在程序一起

**Comment by 171qe** [comment]
> 把 models 里的文件夹放在程序一起

OK好了 感谢
