### ISSUE TITLE
 编译报错

### ISSUE THREAD

**Issue by arccos2002** [nihui/realcugan-ncnn-vulkan#13]
realcugan-ncnn-vulkan/src/ncnn/src/gpu.cpp:3006:47: error: ‘PFN_vkDestroySamplerYcbcrConversionKHR’ was not declared in this scope
         vkDestroySamplerYcbcrConversionKHR = (PFN_vkDestroySamplerYcbcrConversionKHR)vkGetDeviceProcAddr(d->device, "vkDestroySamplerYcbcrConversionKHR");
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ncnn/src/CMakeFiles/ncnn.dir/build.make:509: recipe for target 'ncnn/src/CMakeFiles/ncnn.dir/gpu.cpp.o' failed

ncnn：git上最新版本
cmake：3.22

**Comment by nihui** [comment]
vulkan sdk 版本太旧？

**Comment by arccos2002** [comment]
顺便问下，里面.param和.bin是torch模型转的吗

**Comment by arccos2002** [comment]
最新版vulkan sdk 编译不通过，方便加微信沟通吗，我的微信是github用户名。

**Comment by arccos2002** [comment]
已经解决
