### ISSUE TITLE
palette png图片的图像透明数据块tRNS不能被正确处理的问题

### ISSUE THREAD

**Issue by hokejyo** [nihui/realcugan-ncnn-vulkan#15]
大佬，我又发现一个问题，就是palette png图片的图像透明数据块tRNS放大后透明信息丢失，变成黑色，而且边缘锯齿明显，导致在游戏内不能正常显示，如下图(这个问题在waifu2x-ncnn和real-esrgnn-ncnn中也有出现，亲测将带有tRNS块的palette png图片预处理为RGBA再放大能够解决这个问题)：
<img width="767" alt="Snipaste_2022-03-26_16-32-24" src="https://user-images.githubusercontent.com/92669141/160231682-edccc268-9aac-43a7-9e13-1c575763d9d9.png">
<img width="445" alt="Snipaste_2022-03-26_16-33-05" src="https://user-images.githubusercontent.com/92669141/160231683-f00d7970-7a4d-4797-a209-a4484ee1562d.png">
<img width="949" alt="Snipaste_2022-03-26_16-30-15" src="https://user-images.githubusercontent.com/92669141/160231685-a72b5f63-a1ea-4933-9dcf-d71c9f3cf337.png">
<img width="949" alt="Snipaste_2022-03-26_16-31-20" src="https://user-images.githubusercontent.com/92669141/160231678-6508891f-d507-4184-8945-b64e0ee305d9.png">

**Comment by nihui** [comment]
是什么操作系统？

**Comment by hokejyo** [comment]
> 是什么操作系统？

win10

**Comment by nihui** [comment]
已确认windows平台特有bug

todo
https://docs.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicbitmapdecoder-copypalette
https://docs.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicpalette-hasalpha

**Comment by nihui** [comment]
麻烦用zip打包上传有问题的输入png，用于复现和测试

**Comment by hokejyo** [comment]
> 麻烦用zip打包上传有问题的输入png，用于复现和测试
[palette_png_with_tRNS_chunk.zip](https://github.com/nihui/realcugan-ncnn-vulkan/files/8355355/palette_png_with_tRNS_chunk.zip)
好的！

**Comment by tumuyan** [comment]
实际上rgba放大后也不是非常棒，目前alpha通道是使用bicubic插值的，能否对alpha通道也做一些简单的推理或者复杂一些的处理呢？根据常识，alpha通道可能有如下特征：
1. alpha通道可能与rgb通道的内容相关，rgb通道的边缘同样也是alpha通道的边缘（当rgb通道超分得到光滑曲线时，bicubic得到的alpha通道在对应位置并不是非常锐利，导致最终视觉效果不佳）
2. alpha通道可能具有平滑的梯度（bicubic插值不会对这种情况产生明显劣化）

**Comment by nihui** [comment]
https://github.com/nihui/realcugan-ncnn-vulkan/commit/40e855d53a34d1c983bc7f74fca10c8fe8f941c0
