### ISSUE TITLE
vkAllocateMemory failed -10

### ISSUE THREAD

**Issue by RatLittle** [nihui/realcugan-ncnn-vulkan#19]
![image](https://user-images.githubusercontent.com/84579068/161409547-8357b27e-368d-4836-949d-77cc49808720.png)
如图。内存分配失败？

**Comment by WenDell-es** [comment]
遇到同样问题，ncnn程序仅占用了100MB内存，我的PC还有至少10GB的内存可用，然而程序出现了该错误vkAllocateMemory failed -10 （此问题在处理较大图片时遇到）
