### ISSUE TITLE
tilesize=400的意义是什么？

### ISSUE THREAD

**Issue by yuxiao-ash** [nihui/realcugan-ncnn-vulkan#48]
想请教下以tilesize=400进行分块处理的意义是什么？不了解这个模型，请问下这样分块处理是由于realcugan模型的要求，还是出于ncnn推理超分模型时的性能考虑？

**Comment by nihui** [comment]
分块能减少显存占用

**Comment by yuxiao-ash** [comment]
> 分块能减少显存占用

感谢~
也就是说如果使用的模型更小，或者使用的GPU有更大的显存时，不使用tile理论上会更优一点是吗？

**Comment by nihui** [comment]
> > 分块能减少显存占用
> 
> 感谢~ 也就是说如果使用的模型更小，或者使用的GPU有更大的显存时，不使用tile理论上会更优一点是吗？

能减少多个tile同步的操作，效率更高些
