### ISSUE TITLE
用2021 MPB 16的Apple M1 Pro无法运行

### ISSUE THREAD

**Issue by zouquan741** [nihui/realcugan-ncnn-vulkan#5]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/13255981/154238452-6b8b51d0-6dc3-4788-b7b8-c99f63b91d08.png">
既然编译了arm架构，不能在m1上跑也挺奇怪的。
而且搜了下ncnn应该早就支持m1了？

**Comment by nihui** [comment]
```
cd /Downloads/realcugan-ncnn-vulkan-20220215-macos
./realcugan-ncnn-vulkan -i xxx -o xxx
```

**Comment by zouquan741** [comment]
就是找不到model文件吧？应该给个人话提示或者默认搜可执行文件目录会好点

**Comment by nihui** [comment]
20220216 版本自动获取 macos 二进制文件目录

**Comment by zouquan741** [comment]
> 20220216 版本自动获取 macos 二进制文件目录

<img width="564" alt="image" src="https://user-images.githubusercontent.com/13255981/154421517-bb6613a2-6d70-406c-bf51-76f84af336b7.png">
大佬再看看，没取dirname吧

**Comment by nihui** [comment]
> > 20220216 版本自动获取 macos 二进制文件目录
> 
> <img alt="image" width="564" src="https://user-images.githubusercontent.com/13255981/154421517-bb6613a2-6d70-406c-bf51-76f84af336b7.png">
> 大佬再看看，没取dirname吧

嗯嗯，确实...
感谢反馈

**Comment by nihui** [comment]
20220217 发布了～
