### ISSUE TITLE
3倍放大下输出的图片不正常

### ISSUE THREAD

**Issue by hokejyo** [nihui/realcugan-ncnn-vulkan#7]
其它放大倍率正常，只有3倍下会输出异常图片：
![ev201c](https://user-images.githubusercontent.com/92669141/154389284-6c64844f-4baa-48a7-b240-ea5071d80fd8.png)
![ev101a](https://user-images.githubusercontent.com/92669141/154389338-80d424b1-d44e-47cf-aa08-d4190f587558.png)
参数：
![image](https://user-images.githubusercontent.com/92669141/154389510-64e442e5-43a5-480d-a3e5-1fa51c396baa.png)
报错：
vkAllocateMemory failed -2
vkWaitForFences failed -4
vkWaitForFences failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4

**Comment by nihui** [comment]
20220217 发布了～
试试看

**Comment by hokejyo** [comment]
> 20220217 发布了～ 试试看

大佬，现在单张图片放大是正常的，就是批量放大会间隔一个输出异常图片，报错是相同的
![image](https://user-images.githubusercontent.com/92669141/154500358-77013282-eab9-4e40-94e4-92823e7af2db.png)
还有就是同一显卡3x放大速度是10张/55s，4x放大只要10张/23s，而且还没有异常

**Comment by nihui** [comment]
> > 20220217 发布了～ 试试看
> 
> 大佬，现在单张图片放大是正常的，就是批量放大会间隔一个输出异常图片，报错是相同的 ![image](https://user-images.githubusercontent.com/92669141/154500358-77013282-eab9-4e40-94e4-92823e7af2db.png) 还有就是同一显卡3x放大速度是10张/55s，4x放大只要10张/23s，而且还没有异常

可以尝试调小 tilesize，比如 400 200 这样
3x 比 4x 更消耗显存，也更慢，确实是这样
