### ISSUE TITLE
这是怎么勒

### ISSUE THREAD

**Issue by Goaw1515** [nihui/realcugan-ncnn-vulkan#8]
root@DA151:/home/j/realcugan-ncnn-vulkan/build# ./realcugan-ncnn-vulkan -i /home/a.jpg -o b.png
[0 llvmpipe (LLVM 12.0.0, 128 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 12.0.0, 128 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 12.0.0, 128 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/0
[0 llvmpipe (LLVM 12.0.0, 128 bits)]  subgroup=4  basic=1  vote=1  ballot=1  shuffle=0
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
fopen /home/j/realcugan-ncnn-vulkan/build/models-se/up2x-conservative.param failed
fopen /home/j/realcugan-ncnn-vulkan/build/models-se/up2x-conservative.bin failed
find_blob_index_by_name in0 failed
Try
find_blob_index_by_name gap0 failed
Try
find_blob_index_by_name gap1 failed
Try
find_blob_index_by_name gap2 failed
Try
find_blob_index_by_name gap3 failed
Try
Invalid bitcast
  %347 = bitcast i32 %346 to i16
LLVM ERROR: Broken function
Aborted

**Comment by 1715689942** [comment]
用的是 子系统Ubuntu

**Comment by nihui** [comment]
https://github.com/nihui/realcugan-ncnn-vulkan/releases 这里下载ubuntu版本包
看输出是没有找到支持vulkan的显卡

**Comment by 1715689942** [comment]
> https://github.com/nihui/realcugan-ncnn-vulkan/releases 这里下载ubuntu版本包 看输出是没有找到支持vulkan的显卡

噢噢 知道了

**Comment by 171qe** [comment]
> https://github.com/nihui/realcugan-ncnn-vulkan/releases 这里下载ubuntu版本包 看输出是没有找到支持vulkan的显卡

这个ubuntu版本包 arm64可以用嘛

**Comment by 171qe** [comment]
> https://github.com/nihui/realcugan-ncnn-vulkan/releases 这里下载ubuntu版本包 看输出是没有找到支持vulkan的显卡
![Screenshot_2022_0218_214426](https://user-images.githubusercontent.com/73588816/154694634-7ffddd29-f3fd-47dc-85a1-58412f1df79b.png)
这是怎么了 用的是termux

**Comment by Baiyuetribe** [comment]
我也是如此，rtx2070显卡，Windows正常，WSL2环境下报错如下：
```bash
root@DESKTOP-DNB9LBR:~/wsl2cmake/ncnn/realcugan-ncnn-vulkan-20220318-ubuntu# ./realcugan-ncnn-vulkan -i /root/wsl2cmake/demo.jpg -o out.png
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/0
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  subgroup=8  basic=1  vote=1  ballot=1  shuffle=0
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
Invalid bitcast
  %379 = bitcast i32 %378 to i16
LLVM ERROR: Broken function
Aborted
```
WSL2中可以用`nvidia-sim`，个人开发时使用NCNN调用gpu可正常输出。
